version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: resume-analyzer-backend
    ports:
      - "8000:8000"
    env_file:
      - ./Backend/.env
    volumes:
      - ./Backend:/app
    depends_on:
      - mongodb
    networks:
      - resume-analyzer-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: resume-analyzer-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.production
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - resume-analyzer-network
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    container_name: resume-analyzer-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - resume-analyzer-network

networks:
  resume-analyzer-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local

